[package]
name = "rustracer"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
crossterm = "0.26.1"
image = "0.24.6"
rand = "0.8.5"
rayon = "1.7.0"
